spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: file-storage
  datasource:
    url: jdbc:postgresql://localhost:5432/file-storage
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: validate
        show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true

  flyway:
    url: jdbc:postgresql://localhost:5432/file-storage
    user: admin
    password: admin
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: true
    connect-retries: 50           # Number of retries
    connect-retries-interval: 5s
grpc:
  server:
    port: 9090
    max-inbound-message-size: 100MB