name: Deploy to VPS

on:
  push:
    branches: [master]

env:
  VPS_IP: ${{ secrets.VPS_IP }}
  VPS_USER: ${{ secrets.VPS_USER }}
  SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
  DOCKER_IMAGE: iceteagreen/file-storage:${{ github.run_id }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

#      # Build Java app (only needed for tests)
#      - uses: actions/setup-java@v4
#        with:
#          distribution: 'temurin'
#          java-version: '17'
#
#      - run: mvn package -DskipTests

      # Docker steps
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag and Push
        uses: docker/build-push-action@v5
        with:
          tags: |
            $DOCKER_IMAGE
            iceteagreen/file-storage:latest
          push: true

      # Deployment
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Debug Image Name
        run: |
          echo "Docker image: $DOCKER_IMAGE"

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H $VPS_IP >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Transfer Compose File
        run: |
          ssh -T $VPS_USER@$VPS_IP "mkdir -p /home/file-storage"
          scp -o StrictHostKeyChecking=no \
              docker-compose.prod.yml \
              $VPS_USER@$VPS_IP:/home/file-storage/

      - name: Deploy
        run: |  
          ssh -T $VPS_USER@$VPS_IP <<EOF
          docker pull $DOCKER_IMAGE
          cd /home/file-storage
          docker compose -f docker-compose.prod.yml down  # Remove old containers
          docker compose -f docker-compose.prod.yml up -d --force-recreate  # Create new ones
          EOF